name: angular_ui
version: 0.6.0
authors:
- Sergey Akopkokhyants <akserg@gmail.com>
- Tonis Pool <tonis.pool@gmail.com>
- Gunter Zochbauer <gzoechi@gmail.com>
- Francesco Cina <ufoscout@gmail.com>
- Neeraj Mittal <mittal.neeraj@gmail.com>
description: Port of Angular-UI to Dart.
homepage: http://akserg.github.io/angular.dart.ui
environment:
  sdk: '>=1.7.2 <2.0.0'
dependencies:
  angular: '1.0.0'
dev_dependencies:
  dartmocks: '>= 0.5.0'
  guinness: '>= 0.1.3'
transformers:
- angular:
    html_files:
      - web/buttons/buttons_demo.html
      - web/alert/alert_demo.html
      - web/collapse/collapse_demo.html
      - web/dropdown_toggle/dropdown_toggle_demo.html
      - web/rating/rating_demo.html
