name: angular_ui
version: 0.6.0
authors:
- Sergey Akopkokhyants <akserg@gmail.com>
- Tonis Pool <tonis.pool@gmail.com>
- Gunter Zochbauer <gzoechi@gmail.com>
- Francesco Cina <ufoscout@gmail.com>
- Neeraj Mittal <mittal.neeraj@gmail.com>
description: Port of Angular-UI to Dart.
homepage: http://akserg.github.io/angular.dart.ui
environment:
  sdk: '>=1.6.0 <2.0.0'
dependencies:
  angular: '1.0.0'
dev_dependencies:
  dartmocks: '>= 0.5.0'
  guinness: '>= 0.1.3'
transformers:
- angular:
    html_files:
      - web/buttons/buttons_demo.html
      - web/alert/alert_demo.html
      - web/collapse/collapse_demo.html
      - web/dropdown_toggle/dropdown_toggle_demo.html
      - web/rating/rating_demo.html
      - web/timepicker/timepicker_demo.html
      - web/tooltip/tooltip_demo.html
      - web/pagination/pagination_demo.html
      - web/modal/modal_demo_embedded_template.html
      - web/modal/modal_demo_embedded_template_static_backdrop.html
      - web/modal/modal_demo_template_element.html
      - web/modal/modal_demo_template_from_other_file.html
      - web/accordion/accordion_demo.html
      - web/popover/popover_demo.html